### ISSUE TITLE
vitamio  这个是是吗？需要授权吗

### ISSUE THREAD

**Issue by anjiao** [w1123440793/VideoListDemo#1]
收费的！？？

**Comment by anjiao** [comment]
是什么

**Comment by w1123440793** [comment]
视频播放使用的 ijkplayer  免费的 B站的开源 https://github.com/Bilibili/ijkplayer

**Comment by anjiao** [comment]
那 vitamio  这个 有什么用呢？？我注释掉这个  ，然后就播放不了 说 unknown error
//        if (!io.vov.vitamio.LibsChecker.checkVitamioLibs(this)) {
//            Log.e("tag", "checkVitamioLibs");
//            return;
//        }
        context=this;
//        Vitamio.isInitialized(this);

**Comment by w1123440793** [comment]
去掉了vitamio ,更新就行

**Comment by anjiao** [comment]
嗯 oK
