### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by dds95** [w1123440793/VideoListDemo#8]
点击视频 滑动到下方   关闭小窗口后 在点击第一个 java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.RelativeLayout.setVisibility(int)' on a null object reference
   at cn.demo.videolist.MainActivity$4.onclick(MainActivity.java:148)

有时也会报Performing stop of activity that is not resumed

**Comment by w1123440793** [comment]
已更改
